### ISSUE TITLE
如何处理printf？

### ISSUE THREAD

**Issue by jiec-msft** [375670450/TinyCompiler#3]
我想要做GO语言的编译器，但是不知道如何处理pmf.Println？最后的汇编语言应该如何才能连接起来然后生成二进制代码呢？

**Comment by stardust95** [comment]
1. 如何在IR中实现printf功能？
LLVM提供了这一函数，可以通过getOrInsertFunction函数获取到。
知乎上有一个详细的教程可以参考下：
https://zhuanlan.zhihu.com/p/22498133
2. 如何链接生成可执行文件？
无论要实现c还是golang的编译器，通过LLVM生成的obj文件只是目标文件，可以通过clang、gcc等c/c++编译器来链接成可执行文件。例如：
```bash
# 先通过llvm生成obj文件output.o
./compiler test.input
# 链接obj文件，生成可执行程序
clang output.o -o test
# 执行程序
./test
```

**Comment by jiec-msft** [comment]
谢谢！
